package cc.ataglace.molebutter.imaging.internal.service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.springframework.stereotype.Service;
import cc.ataglace.molebutter.imaging.api.*;
import cc.ataglace.molebutter.imaging.internal.client.ImageDownloadClient;
import cc.ataglace.molebutter.imaging.internal.render.NoticeImageRenderer;
import cc.ataglace.molebutter.imaging.internal.render.ProductPhotoMargin;
import lombok.RequiredArgsConstructor;

/** Keeps the current mixed image order and produces a bounded browser ZIP, without local folders. */
@Service
@RequiredArgsConstructor
public class DownloadService {
    public static final int MAX_ARCHIVE_BYTES = 32 * 1024 * 1024;
    private static final long MAX_CONTENT_BYTES = 64L * 1024 * 1024;
    private final ImageDownloadClient imageDownloadClient;
    private final NoticeImageRenderer noticeImageRenderer;
    private final SizeGuideService sizeGuideService;
    private final GeneratedImageStore generatedSizeImageStore;

    public PreparedDownload downloadImages(Long actor, DownloadRequestDto request, ProductLookupDto product) {
        List<ExportImageDto> images = exportImages(capture(actor, request, product));
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        List<String> names = new ArrayList<>();
        try (ZipOutputStream zip = new ZipOutputStream(new BoundedOutput(bytes))) {
            for (ExportImageDto image : images) add(zip, names, image.fileName(), image.bytes());
        } catch (IOException e) {
            throw new ImagingFailure(ImagingFailure.Kind.INTERNAL, "이미지 ZIP을 만들지 못했습니다.", e);
        }
        return new PreparedDownload(new DownloadResultDto(product.productCode() + ".zip", names), bytes.toByteArray());
    }

    /** Captures owned generated bytes and source indexes without supplier downloads. */
    public ExportSnapshot capture(Long actor, DownloadRequestDto request, ProductLookupDto product) {
        ImagingInputs.actor(actor); ImagingInputs.download(request);
        List<DownloadImageItemDto> items = request.images() == null
                ? (request.imageIndexes() == null ? List.<Integer>of() : request.imageIndexes()).stream()
                    .distinct().map(index -> new DownloadImageItemDto(index, null)).toList()
                : request.images();
        Map<String, GeneratedImageStore.StoredImage> generated = new HashMap<>();
        for (DownloadImageItemDto item : items) {
            if (item.imageIndex() != null && item.imageIndex() >= product.imageUrls().size()) {
                throw new ImagingFailure(ImagingFailure.Kind.INVALID_INPUT, "원본 이미지 번호가 올바르지 않습니다.");
            }
            if (item.imageIndex() != null && item.sourceImageUrl() != null
                    && !item.sourceImageUrl().equals(product.imageUrls().get(item.imageIndex()))) {
                throw new ImagingFailure(ImagingFailure.Kind.INVALID_INPUT, "상품 사진 목록이 변경되었습니다. 상품을 다시 조회해주세요.");
            }
            if (item.generatedImageId() != null) {
                generated.computeIfAbsent(item.generatedImageId(), id -> generatedSizeImageStore.getStored(actor, id, product));
            }
        }
        return new ExportSnapshot(request, product, List.copyOf(items), Map.copyOf(generated));
    }

    public List<ExportImageDto> exportImages(ExportSnapshot selection) {
        DownloadRequestDto request = selection.request();
        ProductLookupDto product = selection.product();
        List<ExportImageDto> files = new ArrayList<>();
        long contentBytes = 0;
        int sequence = 1;
        int sizeSequence = 0;
        int noticeSequence = 0;
        for (DownloadImageItemDto item : selection.items()) {
            GeneratedImageStore.StoredImage snapshot = item.generatedImageId() == null ? null : selection.generated().get(item.generatedImageId());
            ImageDownloadClient.DownloadedImage image = snapshot != null
                    ? new ImageDownloadClient.DownloadedImage(snapshot.png(), "image/png", ".png")
                    : ProductPhotoMargin.apply(imageDownloadClient.downloadProductImage(
                            product.imageUrls().get(item.imageIndex()), product.productCode()));
            contentBytes = checkedContentSize(contentBytes, image.bytes().length);
            String name = "%02d%s".formatted(sequence++, image.fileExtension());
            if (snapshot != null) {
                name = switch (snapshot.kind()) {
                    case SIZE -> sizeFilename(++sizeSequence);
                    case NOTICE -> noticeFilename(++noticeSequence);
                };
            }
            files.add(export(name, image));
        }
        if (request.includeNoticeImage()) {
            byte[] notice = noticeImageRenderer.renderPng(product.notificationFields());
            contentBytes = checkedContentSize(contentBytes, notice.length);
            files.add(export(noticeFilename(++noticeSequence), new ImageDownloadClient.DownloadedImage(notice, "image/png", ".png")));
        }
        if (request.images() == null && request.includeSizeImage()) {
            SizeGuideSelectionDto sizeSelection = request.sizeGuide();
            boolean chosen = sizeSelection != null && sizeSelection.templateKey() != null && !sizeSelection.templateKey().isBlank();
            if (chosen || product.sizeGuideSupported()) {
                byte[] png = sizeGuideService.render(product, sizeSelection).png();
                checkedContentSize(contentBytes, png.length);
                files.add(export(sizeFilename(++sizeSequence), new ImageDownloadClient.DownloadedImage(png, "image/png", ".png")));
            }
        }
        return List.copyOf(files);
    }
    private static ExportImageDto export(String name, ImageDownloadClient.DownloadedImage image) {
        String extension = switch (image.contentType()) {
            case "image/jpeg" -> ".jpg";
            case "image/png" -> ".png";
            case "image/gif" -> ".gif";
            case "image/webp" -> ".webp";
            case "image/avif" -> ".avif";
            default -> throw new ImagingFailure(ImagingFailure.Kind.INTERNAL, "내보낼 이미지 형식을 확인할 수 없습니다.");
        };
        return new ExportImageDto(name, image.contentType(), extension, image.bytes());
    }
    public record ExportSnapshot(DownloadRequestDto request, ProductLookupDto product,
            List<DownloadImageItemDto> items, Map<String, GeneratedImageStore.StoredImage> generated) { }
    private static String sizeFilename(int sequence) {
        return sequence == 1 ? "사이즈.png" : "사이즈_%d.png".formatted(sequence);
    }
    private static String noticeFilename(int sequence) {
        return sequence == 1 ? "상품정보.png" : "상품정보_%d.png".formatted(sequence);
    }
    private static long checkedContentSize(long size, int next) {
        if (size + next > MAX_CONTENT_BYTES) {
            throw new ImagingFailure(ImagingFailure.Kind.INVALID_INPUT, "다운로드 전체 이미지 크기가 64MB를 초과했습니다. 이미지를 나누어 내려받아주세요.");
        }
        return size + next;
    }
    private static void add(ZipOutputStream zip, List<String> names, String name, byte[] bytes) throws IOException {
        zip.putNextEntry(new ZipEntry(name)); zip.write(bytes); zip.closeEntry(); names.add(name);
    }
    public record PreparedDownload(DownloadResultDto metadata, byte[] archive) { }
    private static class BoundedOutput extends OutputStream {
        private final ByteArrayOutputStream out;
        BoundedOutput(ByteArrayOutputStream out) { this.out = out; }
        @Override public void write(int value) {
            if (out.size() >= MAX_ARCHIVE_BYTES) tooLarge();
            out.write(value);
        }
        @Override public void write(byte[] bytes, int offset, int length) {
            if ((long) out.size() + length > MAX_ARCHIVE_BYTES) tooLarge();
            out.write(bytes, offset, length);
        }
        private void tooLarge() { throw new ImagingFailure(ImagingFailure.Kind.INVALID_INPUT, "ZIP 크기가 32MB를 초과했습니다. 이미지를 나누어 내려받아주세요."); }
    }
}
