CREATE TABLE inventory_purchase (
 id BIGINT PRIMARY KEY,
 revision BIGINT NOT NULL DEFAULT 0,
 purchased_on DATE NOT NULL,
 supplier_name VARCHAR(255) NOT NULL DEFAULT '',
 order_number VARCHAR(255) NOT NULL DEFAULT '',
 order_url VARCHAR(2000) NOT NULL DEFAULT '',
 payment_method VARCHAR(100) NOT NULL DEFAULT '',
 payment_alias VARCHAR(100) NOT NULL DEFAULT '',
 paid_on DATE NULL,
 private_note VARCHAR(2000) NOT NULL DEFAULT '',
 created_by BIGINT NOT NULL,
 request_id VARCHAR(36) NOT NULL,
 request_hash VARCHAR(64) NOT NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 UNIQUE KEY ux_inventory_purchase_request(request_id),
 INDEX ix_inventory_purchase_date(purchased_on,id),
 FOREIGN KEY(created_by) REFERENCES `user`(id)
);
CREATE TABLE inventory_item (
 id BIGINT PRIMARY KEY,
 purchase_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 origin_product_id BIGINT NOT NULL,
 supplier_id BIGINT NULL,
 revision BIGINT NOT NULL DEFAULT 0,
 purchased_code VARCHAR(100) NOT NULL,
 purchased_name VARCHAR(1000) NOT NULL DEFAULT '',
 color VARCHAR(100) NOT NULL DEFAULT '',
 size VARCHAR(100) NOT NULL DEFAULT '',
 option_label VARCHAR(500) NOT NULL DEFAULT '',
 external_option_id VARCHAR(200) NOT NULL DEFAULT '',
 original_ordered_quantity BIGINT NOT NULL,
 ordered_quantity BIGINT NOT NULL,
 on_hand BIGINT NOT NULL DEFAULT 0,
 pending BIGINT NOT NULL,
 unit_price BIGINT NULL,
 location VARCHAR(255) NOT NULL DEFAULT '',
 public_note VARCHAR(2000) NOT NULL DEFAULT '',
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY(purchase_id) REFERENCES inventory_purchase(id),
 FOREIGN KEY(product_id) REFERENCES catalog_product(id),
 FOREIGN KEY(origin_product_id) REFERENCES catalog_product(id),
 FOREIGN KEY(supplier_id) REFERENCES product_supplier(id),
 INDEX ix_inventory_item_product(product_id,id),
 INDEX ix_inventory_item_purchase(purchase_id,id),
 CONSTRAINT ck_inventory_item_balances CHECK(ordered_quantity BETWEEN 1 AND 1000000 AND on_hand BETWEEN 0 AND 1000000 AND pending BETWEEN 0 AND ordered_quantity),
 CONSTRAINT ck_inventory_price CHECK(unit_price IS NULL OR unit_price BETWEEN 0 AND 1000000000)
);
CREATE TABLE inventory_movement (
 id BIGINT PRIMARY KEY,
 item_id BIGINT NOT NULL,
 kind VARCHAR(30) NOT NULL,
 quantity BIGINT NOT NULL,
 hand_delta BIGINT NOT NULL,
 pending_delta BIGINT NOT NULL,
 occurred_at DATETIME(6) NOT NULL,
 reason VARCHAR(1000) NOT NULL DEFAULT '',
 reference_number VARCHAR(255) NOT NULL DEFAULT '',
 reference_id BIGINT NULL,
 reverses_id BIGINT NULL,
 actor_id BIGINT NOT NULL,
 request_id VARCHAR(36) NOT NULL,
 request_hash VARCHAR(64) NOT NULL,
 refund_revision BIGINT NOT NULL DEFAULT 0,
 refund_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
 refund_amount BIGINT NULL,
 refunded_on DATE NULL,
 created_at DATETIME(6) NOT NULL,
 FOREIGN KEY(item_id) REFERENCES inventory_item(id),
 FOREIGN KEY(reference_id) REFERENCES inventory_movement(id),
 FOREIGN KEY(reverses_id) REFERENCES inventory_movement(id),
 FOREIGN KEY(actor_id) REFERENCES `user`(id),
 UNIQUE KEY ux_inventory_movement_request(request_id),
 UNIQUE KEY ux_inventory_reversal(reverses_id),
 INDEX ix_inventory_movement_item(item_id,id),
 INDEX ix_inventory_movement_reference(reference_id,kind),
 CONSTRAINT ck_inventory_movement_quantity CHECK(quantity BETWEEN 1 AND 1000000)
);
