const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('molebutter-app/src/main/resources/static/js/marketplace-orders.js','utf8');
const model=require('../../../molebutter-app/src/main/resources/static/js/marketplace-orders.js');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function setup(history=[]){const elements={},reads=[],writes=[],events={},timers=[],histories=[];let uuid=0;
 const get=id=>elements[id]??={value:id==='orders-size'?'10':'',hidden:true,disabled:false,open:false,textContent:'',innerHTML:'',listeners:{},showModal(){this.open=true;},close(){this.open=false;this.listeners.close?.();},replaceChildren(){this.innerHTML='';},addEventListener(event,fn){this.listeners[event]=fn;},querySelector(){return get('orders-query-submit');},querySelectorAll(selector){if(selector.includes(':checked'))return [{value:'COUPANG'}];return [];}};
 const ctx={FormActions:{bindEnterSubmit(form,button){assert.equal(form,get('orders-query'));assert.equal(button,get('orders-query-submit'));},bindExplicitSubmit(form,button,handler){button.type='button';form.addEventListener('submit',event=>event.preventDefault());button.addEventListener('click',()=>handler({preventDefault(){}}));}},AppUI:{$:get,uuid:()=>`uuid-${++uuid}`,escape:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')},Date,URLSearchParams,document:{},window:{addEventListener:(name,fn)=>events[name]=fn},setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){},apiGet:(url,options)=>url==='/api/marketplace-orders/collections'?(history===null?new Promise((resolve,reject)=>histories.push({resolve,reject})):Promise.resolve(history)):new Promise((resolve,reject)=>reads.push({url,options,resolve,reject})),apiRequest:(url,options)=>new Promise((resolve,reject)=>writes.push({url,options,resolve,reject}))};
 vm.runInNewContext(source,ctx);return {get,reads,writes,events,timers,histories,submit:id=>get(id).listeners.submit({preventDefault(){}}),click:id=>get(id).listeners.click(),detail:(market,id)=>get('orders-rows').listeners.click({target:{closest:()=>({dataset:{orderMarket:market,orderId:id}})}})};
}
const row=(name='상품')=>({market:'COUPANG',orderId:'99999999999999999999',shipmentBoxId:'8',productName:name,quantity:0,orderPrice:{currency:'KRW',amount:'0'},claims:[]});
const page=(name='상품',total=1)=>({items:[row(name)],page:0,size:10,total});
test('KST recent seven days, inclusive maximum31 and distinct market order keys',()=>{assert.deepEqual(model.recentDates(new Date('2026-10-06T15:01:00Z')),{from:'2026-10-01',to:'2026-10-07'});assert.equal(model.dateError('2026-10-01','2026-10-31'),'');assert.match(model.dateError('2026-10-01','2026-11-01'),/31/);assert.match(model.dateError('2026-10-03','2026-10-01'),/종료/);assert.notEqual(model.orderKey({...row(),market:'NAVER'}),model.orderKey(row()));assert.equal(model.money(null),'미확인');assert.equal(model.money({currency:'KRW',amount:'0'}),'0원');});
test('list uses no-store, safe rendering, preserves zero and discards stale responses',async()=>{const s=setup();assert.equal(s.reads[0].options.cache,'no-store');s.submit('orders-query');s.reads[1].resolve(page('<unsafe>'));await flush();s.reads[0].resolve(page('stale'));await flush();assert.match(s.get('orders-rows').innerHTML,/&lt;unsafe>/);assert(!s.get('orders-rows').innerHTML.includes('stale'));assert.match(s.get('orders-rows').innerHTML,/0원/);assert(!s.get('orders-rows').innerHTML.includes('undefined'));s.get('orders-size').value='50';s.get('orders-size').listeners.change();assert.match(s.reads[2].url,/size=50/);});
test('live detail clears PII on close, ignores late responses and suppresses duplicate reads',async()=>{const s=setup();s.reads[0].resolve(page());await flush();s.detail('COUPANG','8');s.detail('COUPANG','8');assert.equal(s.reads.length,2);assert.equal(s.reads[1].options.cache,'no-store');s.reads[1].resolve({shipments:[{shipmentBoxId:'1',recipientName:'<name>',phone:'010-1234',address:'address'}],items:[]});await flush();assert.match(s.get('orders-detail-content').innerHTML,/010-1234/);s.click('orders-detail-close');assert.equal(s.get('orders-detail-content').innerHTML,'');s.detail('COUPANG','9');s.click('orders-detail-close');s.reads[2].resolve({shipments:[{recipientName:'late secret'}],items:[]});await flush();assert.equal(s.get('orders-detail-content').innerHTML,'');});
test('collection retry retains request ID after lost response and cancellation stops polling',async()=>{const s=setup();s.reads[0].resolve({items:[],page:0,size:10,total:0});await flush();s.click('orders-collect');s.click('orders-collect');assert.equal(s.writes.length,1);const first=JSON.parse(s.writes[0].options.body);s.writes[0].reject(Error('lost'));await flush();s.click('orders-collect');assert.equal(JSON.parse(s.writes[1].options.body).requestId,first.requestId);s.writes[1].resolve({id:'job',status:'RUNNING',dateFrom:first.dateFrom,dateTo:first.dateTo,markets:[{market:'COUPANG',status:'RUNNING',count:0}]});await flush();assert.equal(s.get('orders-cancel').hidden,false);s.click('orders-cancel');assert.match(s.writes[2].url,/job\/cancel$/);s.writes[2].resolve({id:'job',status:'CANCELLED',markets:[]});await flush();assert.equal(s.get('orders-cancel').hidden,true);assert.equal(s.get('orders-retry').hidden,false);});
test('pagehide removes shipping detail and late responses cannot restore it',async()=>{const s=setup();s.detail('COUPANG','1');s.events.pagehide();s.reads[1].resolve({shipments:[{recipientName:'secret'}],items:[]});await flush();assert.equal(s.get('orders-detail-content').innerHTML,'');assert(!source.includes('sessionStorage'));assert(!source.includes('localStorage'));});

test('claim and date filters travel to the server without browser persistence',()=>{const s=setup();s.get('orders-claim').value='RETURN';s.get('orders-date-basis').value='CLAIM';s.get('orders-query-from').value='2026-10-01';s.get('orders-query-to').value='2026-10-07';s.submit('orders-query');const query=new URLSearchParams(s.reads[1].url.split('?')[1]);assert.equal(query.get('claimType'),'RETURN');assert.equal(query.get('dateBasis'),'CLAIM');assert.equal(query.get('dateFrom'),'2026-10-01');assert.equal(query.get('dateTo'),'2026-10-07');});

test('reload restores latest persisted collection and polls it without storage',async()=>{const s=setup([{id:'persisted',status:'RUNNING',dateFrom:'2026-10-01',dateTo:'2026-10-07',markets:[{market:'COUPANG',status:'RUNNING',count:3}]}]);await flush();assert.match(s.get('orders-job-summary').textContent,/수집 중/);assert.equal(s.get('orders-job-history').value,'persisted');assert.equal(s.get('orders-cancel').hidden,false);assert(s.timers.length>0);s.timers.at(-1)();assert.equal(s.reads[1].url,'/api/marketplace-orders/collections/persisted');s.reads[1].resolve({id:'persisted',status:'COMPLETED',markets:[]});await flush();});

test('confirmed Korean states and string amounts retain unknowns and large values',()=>{assert.equal(model.orderStatus('COUPANG','ACCEPT'),'결제완료');assert.equal(model.orderStatus('COUPANG','NEW_STATUS'),'NEW_STATUS');assert.equal(model.orderStatus('NAVER','ACCEPT'),'ACCEPT');assert.equal(model.claimLabel({type:'EXCHANGE',status:'PROGRESS',linked:true}),'교환 · 진행');assert.equal(model.claimLabel({type:'RETURN',status:'UNKNOWN',linked:true}),'반품 · UNKNOWN');assert.equal(model.money({currency:'KRW',amount:'99999999999999999999'}),'99999999999999999999원');});

test('progress distinguishes orders items claims unknown and keeps completed work on retry',async()=>{const s=setup([{id:'partial',status:'PARTIAL',dateFrom:'2026-10-01',dateTo:'2026-10-07',currentStage:'ORDER_DETAIL',progress:{orders:2,items:4,claims:3,unknown:1,completedCheckpoints:2,totalCheckpoints:7,failedDetails:1},checkpoints:[{status:'FAILED'}],failures:[{source:'ACCEPT',stage:'ORDER_DETAIL',code:'RESPONSE',dateFrom:'2026-10-01',dateTo:'2026-10-01',orderId:'99999999999999999999',message:'<safe>'}],markets:[]}]);await flush();const progress=s.get('orders-job-progress').innerHTML;assert.match(progress,/구간 2 \/ 7 완료/);assert.match(progress,/실패 1구간/);assert.match(progress,/주문 상세 조회/);for(const name of ['주문','상품','클레임','미확인'])assert(progress.includes('<dt>'+name+'</dt>'));assert.match(s.get('orders-job-retry-note').textContent,/완료된 2구간을 유지/);assert.match(s.get('orders-job-failure-content').innerHTML,/2026-10-01/);assert.match(s.get('orders-job-failure-content').innerHTML,/RESPONSE/);assert.match(s.get('orders-job-failure-content').innerHTML,/&lt;safe>/);assert(!progress.includes('%'));});
test('late initial history cannot replace a newly collected selection or its progress',async()=>{const s=setup(null);s.click('orders-collect');s.writes[0].resolve({id:'new',status:'RUNNING',markets:[]});await flush();assert.equal(s.histories.length,2);s.histories[1].resolve([{id:'new',status:'RUNNING',markets:[]}]);await flush();s.histories[0].resolve([{id:'old',status:'FAILED',markets:[]}]);await flush();assert.equal(s.get('orders-job-history').value,'new');assert(!s.get('orders-job-history').innerHTML.includes('old'));assert.match(s.get('orders-job-summary').textContent,/수집 중/);});
test('live shipping and stored claim timestamps are separated and repeated claims deduplicate',async()=>{const s=setup();s.detail('COUPANG','8');const item={...row(),claims:[{id:'claim-1',type:'RETURN',status:'RETURNS_UNCHECKED',quantity:0,updatedAt:'2026-10-01T10:00:00',linked:true,latestVerified:true}]};s.reads[1].resolve({fetchedAt:'2026-10-07T12:30:00Z',storedCollectedAt:'2026-10-06T09:00:00Z',shipments:[{shipmentBoxId:'1',recipientName:'private',status:'ACCEPT'}],items:[item,item]});await flush();const html=s.get('orders-detail-content').innerHTML;assert.match(html,/최신 조회 · 2026-10-07 21:30:00 KST/);assert.match(html,/저장 관측 · 2026-10-06 18:00:00 KST/);assert.equal((html.match(/<h4>반품 · 반품접수<\/h4>/g)||[]).length,1);assert.match(html,/단가/);assert.match(html,/취소 수량/);s.click('orders-detail-close');assert.equal(s.get('orders-detail-content').innerHTML,'');});
test('collection completion preserves submitted search and current page',async()=>{const s=setup([{id:'job',status:'RUNNING',markets:[]}]);s.reads[0].resolve({...page(),page:2,total:100});await flush();s.get('orders-search').value='unsent';s.timers.at(-1)();s.reads[1].resolve({id:'job',status:'SUCCEEDED',markets:[]});await flush();const params=new URLSearchParams(s.reads[2].url.split('?')[1]);assert.equal(params.get('page'),'2');assert.equal(params.get('query'),'');assert.equal(s.get('orders-search').value,'unsent');});

test('back-forward cache restores querying without restoring shipping PII',async()=>{const s=setup();s.reads[0].resolve({...page(),page:1,total:100});await flush();s.detail('COUPANG','8');s.reads[1].resolve({shipments:[{recipientName:'private'}],items:[]});await flush();s.events.pagehide();s.events.pageshow({persisted:true});assert.equal(s.get('orders-detail-content').innerHTML,'');assert.equal(s.get('orders-detail').open,false);assert.equal(new URLSearchParams(s.reads[2].url.split('?')[1]).get('page'),'1');s.reads[2].resolve({...page('restored'),page:1,total:100});await flush();assert.match(s.get('orders-rows').innerHTML,/restored/);});

test('claims preserve observed status and mark only unverified latest state',async()=>{const s=setup();const claims=[{id:'one',type:'RETURN',status:'RETURNS_COMPLETED',latestVerified:false},{id:'two',type:'EXCHANGE',status:'NEW_STATE'},{id:'three',type:'RETURN',status:'RETURNS_UNCHECKED',latestVerified:true}];s.reads[0].resolve({...page(),items:[{...row(),claims}]});await flush();const list=s.get('orders-rows').innerHTML;assert.match(list,/반품 · 반품완료/);assert.match(list,/교환 · NEW_STATE/);assert.equal((list.match(/최신 미확인/g)||[]).length,2);s.detail('COUPANG','8');s.reads[1].resolve({shipments:[],items:[{...row(),claims}]});await flush();assert.equal((s.get('orders-detail-content').innerHTML.match(/최신 미확인/g)||[]).length,2);s.click('orders-detail-close');assert.equal(s.get('orders-detail-content').innerHTML,'');});
test('historical reconstructed counts are visibly distinguished from exact counts',async()=>{const p={orders:1,items:2,claims:3,unknown:0,completedCheckpoints:1,totalCheckpoints:2,reconstructed:true};const s=setup([{id:'old',status:'PARTIAL',progress:p,markets:[{market:'COUPANG',status:'PARTIAL',progress:{...p,reconstructed:false}}]}]);await flush();assert.match(s.get('orders-job-progress').innerHTML,/복원 수치/);assert(!s.get('orders-job-markets').innerHTML.includes('복원 수치'));});

 test('claim-only detail has product metadata without fake shipping or a retry prompt',async()=>{const s=setup();s.detail('COUPANG','8');s.reads[1].resolve({unavailableReason:'ORDER_UNAVAILABLE',storedCollectedAt:'2026-10-07T00:00:00Z',shipments:[],items:[{status:'ORDER_UNAVAILABLE',claims:[{type:'RETURN',id:'r1',status:'RETURNS_COMPLETED',quantity:1,purchaseQuantity:2,productName:'모의 상품',optionName:'블랙',vendorItemId:'9007199254740993',latestVerified:true}]}]});await flush();const html=s.get('orders-detail-content').innerHTML;assert.match(html,/취소·반품 내역만 조회 가능/);assert.match(html,/모의 상품/);assert.match(html,/9007199254740993/);assert.match(html,/클레임 응답 주문 수량/);assert(!html.includes('최신 조회'));assert(!html.includes('수령자'));assert.equal(s.get('orders-detail-retry').hidden,true);});
 test('placeholder orders are separated from real products in the total',async()=>{const s=setup();s.reads[0].resolve({...page(),productTotal:0,claimOnlyTotal:1,items:[{...row(),quantity:null,status:'ORDER_UNAVAILABLE',claims:[{productName:'클레임 상품',type:'RETURN',status:'RETURNS_COMPLETED'}]}]});await flush();assert.match(s.get('orders-summary').textContent,/상품 0건 · 발주서 미확보 주문 1건/);assert.match(s.get('orders-rows').innerHTML,/클레임 상품/);assert.match(s.get('orders-rows').innerHTML,/클레임 상세/);});

test('collection form submission cannot start a write without the explicit button',()=>{const s=setup();s.submit('orders-collect-form');assert.equal(s.writes.length,0);assert.equal(s.get('orders-collect').type,'button');});
