const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../../../molebutter-app/src/main/resources/static/js/naver-product-editor-model.js');
const {P,D,S}=M;
function valid(){const d=M.fresh();Object.assign(d.fields,{[P+'name']:'합성 상품',[P+'leafCategoryId']:'50000001',[P+'salePrice']:'0',[P+'stockQuantity']:'0',[D+'afterServiceInfo.afterServiceTelephoneNumber']:'02-1234-5678',[D+'afterServiceInfo.afterServiceGuideContent']:'합성 안내',[D+'originAreaInfo.originAreaCode']:'00'});d.images=[{id:crypto.randomUUID(),url:'https://assets.molebutter.link/products/mock/01.png',representative:true}];d.description='<p>합성 설명</p>';M.selectNotice(d,'BAG');for(const f of M.notices.BAG.fields)if(f.required&&f.type==='text')d.fields[M.noticeKey].bag[f.name]='상품 상세페이지 참조';return d;}
test('SmartStore schema notice keys and shared five fields match SOURCE',()=>{assert.equal(Object.keys(M.notices).length,36);for(const [type,meta] of Object.entries(M.notices)){assert.match(type,/^[A-Z_]+$/);for(const field of ['returnCostReason','noRefundReason','qualityAssuranceStandard','compensationProcedure','troubleShootingContents'])assert(meta.fields.some(f=>f.name===field&&f.required&&f.type==='reference'));}assert.equal(M.notices.BAG.fields.length,13);});
test('zero price and stock survive typed payload; NONE emits no option structure',()=>{const d=valid();assert.deepEqual(M.validate(d),[]);const p=M.input(d);assert.equal(p.fields[P+'salePrice'],0);assert.equal(p.fields[P+'stockQuantity'],0);assert.equal(p.fields[D+'minorPurchasable'],true);assert.deepEqual(p.optionNames,[]);assert.deepEqual(p.options,[]);});
test('UUID option combinations map independently of array order and reject duplicates',()=>{const d=valid();d.optionMode='COMBINATION';d.options=[M.blankOption(1),M.blankOption(1)];d.options[0].values=['블랙'];d.options[1].values=['브라운'];const ids=d.options.map(o=>o.id);d.options.reverse();const p=M.input(d);assert.equal(p.options[0].id,ids[1]);assert.equal(p.options[0].price,0);assert.equal(p.options[0].stockQuantity,0);assert.deepEqual(M.validate(d),[]);d.options[0].values=['블랙'];assert(M.validate(d).some(e=>e.message.includes('중복 없이')));});
test('notice switching replaces inactive notice branches in exact request',()=>{const d=valid();d.fields[M.noticeKey].etc={itemName:'비활성'};assert.deepEqual(Object.keys(M.input(d).fields[M.noticeKey]),['productInfoProvidedNoticeType','bag']);M.selectNotice(d,'ETC');assert.equal(d.fields[M.noticeKey].productInfoProvidedNoticeType,'ETC');assert(!('bag' in d.fields[M.noticeKey]));assert.equal(d.fields[M.noticeKey].etc.returnCostReason,'1');});
test('failed uploads keep File and block preparing local blob URLs',()=>{const d=valid();d.images.push({id:crypto.randomUUID(),url:'blob:local',local:true,file:{name:'kept.png'},error:'실패'});assert(M.validate(d).some(e=>e.path==='images'));assert.throws(()=>M.input(d),/업로드/);assert.equal(d.images[1].file.name,'kept.png');});
test('drag image insertion changes representative and order with 9 extra cap',()=>{const images=Array.from({length:10},(_,n)=>({id:String(n),representative:n===0,url:'https://assets.test/'+n}));assert(M.moveImage(images,8,'additional',2));assert.equal(images[2].id,'8');assert(M.moveImage(images,8,'representative'));assert.equal(images[0].id,'7');assert.equal(images.filter(i=>i.representative).length,1);assert(!M.moveImage(images,0,'additional'));assert.deepEqual(images.map(i=>i.order),Array.from({length:10},(_,n)=>n));});
test('read-only group products are blocked and unknown existing option structures preserved',()=>{const d=valid();d.optionMode='PRESERVE';d.optionNames=[];d.options=[];assert.equal(M.input(d).optionMode,'PRESERVE');assert(M.validate(d,{groupProduct:true},'edit').some(e=>e.path==='product'));});
test('server refresh preserves user edits by UUID while rebasing untouched values',()=>{const before=valid();before.optionMode='COMBINATION';before.options=[M.blankOption(1)];before.options[0].values=['블랙'];const edited=structuredClone(before);edited.options[0].stockQuantity='3';const fresh=structuredClone(before);fresh.options[0].price='1200';fresh.fields[P+'name']='반영 상품';const rebased=M.rebase(before,edited,fresh);assert.equal(rebased.options[0].stockQuantity,'3');assert.equal(rebased.options[0].price,'1200');assert.equal(rebased.fields[P+'name'],'반영 상품');});
test('description preview has 800px one-column images and no script or request permission',()=>{const html=M.preview('<img src="https://image.test/a.jpg"><img src="https://image.test/b.jpg">');assert(html.includes('max-width:800px'));assert(html.includes('display:block'));assert(html.includes("script-src 'none'"));assert(html.includes("connect-src 'none'"));});
test('certification IDs and mark are typed, empty date clears, and object notice dates survive',()=>{const d=valid();d.fields[M.certKey]=[{certificationInfoId:'12',certificationKindType:'KC_CERTIFICATION',certificationNumber:'synthetic',certificationMark:'false',certificationDate:''}];M.selectNotice(d,'SEASON_APPLIANCES');d.fields[M.noticeKey].seasonAppliances.releaseDate={year:2026,month:'OCTOBER',monthValue:10,leapYear:false};const p=M.input(d);assert.equal(p.fields[M.certKey][0].certificationInfoId,12);assert.equal(p.fields[M.certKey][0].certificationMark,false);assert.equal(p.fields[M.certKey][0].certificationDate,null);assert.deepEqual(p.fields[M.noticeKey].seasonAppliances.releaseDate,d.fields[M.noticeKey].seasonAppliances.releaseDate);assert.equal(M.notices.SEASON_APPLIANCES.fields.find(f=>f.name==='releaseDate').type,'month');});
test('empty discount is allowed while a configured discount needs its unit',()=>{const d=valid(),key=P+'customerBenefit.immediateDiscountPolicy.discountMethod.';d.fields[key+'value']='';assert.deepEqual(M.validate(d),[]);assert.equal(M.input(d).fields[key+'value'],null);d.fields[key+'value']='1000';assert(M.validate(d).some(e=>e.path==='discount'));d.fields[key+'unitType']='WON';assert.deepEqual(M.validate(d),[]);});
module.exports={valid};
